### PR TITLE
Add DialTimeout API

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by stevenroose** [comment]
Why merge this here and not upstream?

**Comment by dajohi** [comment]
We can try.  https://github.com/samuel/go-socks/pull/3

But we can get this in now if upstream doesn't merge.

**Comment by jrick** [comment]
Since upstream is unresponsive i'm ok with adding this to our fork.

That said I think it can be simplified by using the zero value for a timeout, for the non-timeout version.  See https://golang.org/src/net/dial.go#L259 for the two Dial calls.  Both create a dialer and call it's Dial method, but the non-timeout version leaves the timeout as the zero value.

**Review by jrick — APPROVED** [review]

**Comment by jrick** [comment]
@davecgh might need your review too since I don't have write access to this repo.

**Review by davecgh — APPROVED** [review]
OK

**Pull request merged**
